---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: egov-pod-user
  namespace: default
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
   name: egovpodread
   namespace: default
rules:
 - apiGroups: [""]
   resources: ["pods"]
   verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
   name: egovpodbinding
   namespace: default
subjects:
 - kind: ServiceAccount
   name: egov-pod-user
   namespace: default
roleRef:
   kind: Role
   name: egovpodread
   apiGroup: rbac.authorization.k8s.io